name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag srivathsan99\github_action_image
      
    - name: Run tests in Docker container
      run: docker run -e CI=true srivathsan99\github_action_image npm run test      
